### ISSUE TITLE
tvhgooglemapi-0.8.3.msi wrong version

### ISSUE THREAD

**Issue by ecolint** [jankeirse/tvhgooglemapi#36]
Dear support,

When I install the tvhgooglemapi-0.8.3.msi file from the following page:
https://drive.google.com/a/ecolint.ch/folderview?id=0B5rR8r10bVzvQklLN0cxMEFFWXM&usp=sharing#list

The Control Panel shows tvhgooglemapi version 0.8.2 instead of 0.8.3.

**Comment by jankeirse** [comment]
Indeed, I forgot to update the version number in the msi installer, thanks for reporting. I updated it to reflect the proper version number now.
