### ISSUE TITLE
windows 7 32 bit: Could not send your mail, exitcode of gmaildrafter was 2

### ISSUE THREAD

**Issue by JHPArizona** [jankeirse/tvhgooglemapi#42]
Just installed using the tvhgooglemapi-0.8.3.msi installer. Tried out using the windows explorer context menu, send to mail recipient. 
I reliably get this error message. "Could not send your mail, exitcode of gmaildrafter was 2"
Image attached. I tried what I found in another issue.

Open DOS prompt, 
c:>cd "C:\Program Files (x86)\tvhgooglemapi"
C:\Program Files (x86)\tvhgooglemapi>java -jar gmaildrafter.jar

Note: in my case, there is only the Program Files folder since installation is 32bit. This command works and opens an empty draft in my gmail tab. I am using chrome with the gmail tab fixer extension. Which, by the way, thank you for pointing this out. I have on different occasions ended up with multiple gmail tabs open which is NOT what I wanted. Hopefully this extension will fix those patience trying occasions. 

Based on the command line working, I am making the assumption it has to be something with the tvhgooglemapi.dll, associated files or system permissions or some combination there of.

After testing in cmd prompt, I tried from Explorer on different file types in different folders, all with same result. Using jpeg file, I was asked what size to send the image in, but after accepting default size, gmaildrafter error was displayed.

I am willing to do any testing you need. A note, I did not reboot the system since it did not ask for it and since the gmaildrafter.jar is working as expected, at least from cmd prompt.

![image](https://cloud.githubusercontent.com/assets/13480507/8870115/2f6159a8-31a0-11e5-8f02-3aa51da978c0.png)

**Comment by jankeirse** [comment]
Could you restart just to make sure? The error messages are caused by IO exceptions, which is a bit odd to occur when called from another application but not from the command prompt. 
Do you have a local firewall or antivirus running that could be blocking it?

**Comment by JHPArizona** [comment]
Tried restart, send to mail was the first 'app' I tried and same error result. Of course I have a firewall and antivirus, not safe to use Windows on Internet without. I am running AVG with realtime protection enabled and Ad-Aware with realtime protection off (just manual scan). Firewall is MS OS. I disabled both and firewall all at same time and still same problem.

**Comment by tedlwsn** [comment]
Try to Update your Java to the latest version if its not already. I had this happen on a laptop that had Java 7 Update 75. It wouldn't work till it was updated to the latest release.

**Comment by JHPArizona** [comment]
Thanks Ted! That fixed it. I was running Version 8.45 but installed the latest 8.51. I also allowed it to remove 6.xx which may or may not have had an affect on the problem. I am able to use send to from the context menu.
