### ISSUE TITLE
Can't login with a new account...

### ISSUE THREAD

**Issue by arouthier** [jankeirse/tvhgooglemapi#45]
Hi,

I used TVHGoogleMapi with another account on a computer before, and we switch the user on this computer but we can't login with the new user account on tvhgooglemapi, even with the good password...

I really don't know why i can't login...i tryed to reset the password and we always get the invalid password message...

Can you help us please?

Thanks

**Comment by jankeirse** [comment]
Your answer is probably here: https://lists.exim.org/lurker/message/20150831.183913.650bb6ba.en.html

**Comment by arouthier** [comment]
Hi,

I tried your solution but we keep getting the wrong password message.

**Comment by jankeirse** [comment]
Does this help? https://support.google.com/accounts/answer/6009563?vid=1-635790400077101136-2917816429 
I assume you have enabled imap?

**Comment by arouthier** [comment]
Hi Jan,

It's working now!

Thanks a lot for your help.

Your tool is very usefull.




*Alexis Routhier*

*Intégrateur Logiciel*


T  1-418-956-5922 / 1-514-266-9774

*________________________________________________________________*





1788, chemin de la Canardière, Québec (Qc) G1J 2E3

1, Place Ville Marie, bur. 2001, Montréal (Qc) H3B 2C4


2015-09-28 8:29 GMT-04:00 Jan Keirse <notifications@github.com>:
