### ISSUE TITLE
Invalid Text coding in message

### ISSUE THREAD

**Issue by JojinoS** [jankeirse/tvhgooglemapi#47]
Hi, great tool, but it does scramble the non-english characters, I think the coding is not good. Instead of some special national characters (Slovak) it shows a questionmarks , etc....see picture.
![image](https://cloud.githubusercontent.com/assets/16004159/11376047/dd3d4a2e-92de-11e5-9ac6-7b9cd9df7a47.png)
Anyway great tool. Jozef

**Comment by jankeirse** [comment]
This issue dupplicates https://github.com/jankeirse/tvhgooglemapi/issues/2
