### ISSUE TITLE
Signature issue

### ISSUE THREAD

**Issue by JojinoS** [jankeirse/tvhgooglemapi#48]
I dont know if this is issue, or simply it wasnt meant to work that way, but 
- when the program opens a draft message, normally gmail puts the default signature there...not in this case, which is shame.....
  All the signatures in multiple user enviroment are being updated centrally, say on gmail with external tools, having another html to attach with each user, and keep it updated is not possible.
  Any idea how to use the default signature would be highly apreciated. Thanks , Jozef

**Comment by jankeirse** [comment]
We do this by automatically putting the .html files in every user's folder. As part of https://github.com/jankeirse/tvhgooglemapi/issues/33 this could be implemented by downloading the signature from gmail, but I have not currently scheduled development of that feature and am not aware of anyone else working on it. In the current implementation what you want is not available.
