### ISSUE TITLE
File name in Hebrew

### ISSUE THREAD

**Issue by Muhandes** [jankeirse/tvhgooglemapi#52]
First, a thank you. I was looking for something like that for a long time and just found out it exists, your work is much appreciated.

This may not be a major issue but it is a bit annoying. When a file with a name in Hebrew is attached it comes out as Russian . For example СзйФ ЬФийЭ ЬЮбв СРие.doc instead of בקשה להרשם למסע בארץ.doc

I attached an empty file for testing purposes

Best regards

[בקשה להרשם למסע בארץ.docx](https://github.com/jankeirse/tvhgooglemapi/files/185656/default.docx)

**Comment by jankeirse** [comment]
this is issue https://github.com/jankeirse/tvhgooglemapi/issues/2
