### ISSUE TITLE
error gmaildrafter

### ISSUE THREAD

**Issue by tejotayyz** [jankeirse/tvhgooglemapi#53]
"could not send your mail, exit code of gmaildrafter was 1 most likely reasons are that java is not installed, older than 1.7 or not in the WINDOWS PATH variable.''

how do I solve this error? I'm using Windows 10 and I get this error when I tried to email a .pdf file from within Adobe Acrobat. Java is up to date and I'm not sure what to do to check path.

**Comment by jankeirse** [comment]
If you start cmd.exe and there run this command:
java -jar "c:\Program Files (x86)\tvhgooglemapi\gmaildrafter.jar"
What is the output? It should open a new draft in your browser.

**Comment by tejotayyz** [comment]
Thanks, seems to work now, tried with your script first and then afterwards with acrobat- both opened up gmail draft. Thanks.
