### ISSUE TITLE
"Mail system failure. Check your mail installation" Error, etc.

### ISSUE THREAD

**Issue by hmiedemann** [jankeirse/tvhgooglemapi#55]
Hi there,
First off, I love this software. Thank you for making it. I am an IT guy at a large building corporation. Just in the last week I have had 2 employees come to me with the same issue. An error pops up from Excel that reads:

"Mail system failure. Check your mail installation."

The error is different in Word, it reads:

"Word couldn't send mail because of MAPI failure: "Login failure". (I am entering the correct credentials) 
This error can occur if you attempt to send a Word document as an e-mail attachment in Word and the MAPI session was closed and Word is no longer able to connect to that MAPI session. It can also occur if there is a problem with the fax configuration.
To correct a MAPI related error: restart the MAPI e-mail program (for example,Outlook) or save and close the document, and then restart Word after restarting your MAPI e-mail application. Word will establish a new MAPI session, allowing the document to be sent.
To correct a problem with the fax configuration, review the configuration settings for your fax software and make the appropriate changes."

The employees did nothing in changing configuration or anything. The issue just started randomly. I have tried uninstalling and reinstalling every version of tvhgooglemapi, which did not fix the issue. I did put a debuggmaildrafter file in my temp folder, here are the contents of that file after the error is produced:

c:\windows\system32\cmd.exe  /C java.exe -Dfile.encoding=UTF8 -jar "C:\Program Files (x86)\tvhgooglemapi\gmaildrafter.jar"  -a "C:\Users\miedemah\AppData\Local\Temp\7908.tmp" -n "Book1.xlsx" -b "C:\Users\miedemah\AppData\Local\Temp\tvh7918.tmp" -d --subjectfile "C:\Users\miedemah\AppData\Local\Temp\tvh7919.tmp" --deletesubjectfile

Any help is much appreciated. Again, I absolutely love that you made this software - it makes emailing attachments much easier for our older, less tech savvy employees; especially after the switch over to Google and Gmail was very difficult for them. 

Thanks again,
Hayden

**Comment by jankeirse** [comment]
What happens if you try this:
Create a file c:\subject.txt with notepad.exe containing the subject for the mail, another file with c:\body.txt containing the body for the mail. An Excel file called c:\book.xlsx and then from cmd.exe you launch this command:
c:\windows\system32\cmd.exe /C java.exe -Dfile.encoding=UTF8 -jar "C:\Program Files (x86)\tvhgooglemapi\gmaildrafter.jar" -a "c:\book.xlsx" -n "Book1.xlsx" -b "C:\body.txt" --subjectfile "c:\subject.txt"

**Comment by hmiedemann** [comment]
Jan,
I will try this after hours today when my employees head home. I will let you know my findings in a few hours. Thank you for the response!

**Comment by hmiedemann** [comment]
Hi Jan,
I tried what you had mentioned above, here is the error trace I received in the command prompt:

![image](https://cloud.githubusercontent.com/assets/17646386/16208696/5e6911ca-3701-11e6-954a-75e1733a1ead.png)

It seems like it is showing something to do with an IMAP error, but I can assure you that I have IMAP enabled in the Gmail account settings from which I am trying to send this message. I have not made any config changes to enable IMAP anywhere else, though. I am not very familiar with all of this email configuration, so perhaps I am missing something? I did stumble across this email, but seems like a workaround from your software completely: http://www.howtogeek.com/howto/microsoft-office/use-gmail-imap-in-microsoft-outlook-2007/

Please let me know if you have any other insight.

Thank you!

**Comment by jankeirse** [comment]
Does it work with another user on the same computer? It looks a bit like there's a firewall or some such thing blocking it.

**Comment by hmiedemann** [comment]
It doesn't work with 2 users on the same computer. I have also had the same issue on a separate computer (on the same network) but it happened with Microsoft Office 2007 products. Now I just tried it on my computer with Office 2013 (on the same network, same firewall settings, etc.) and it worked for me. I am beginning to think it is an issue with Office 2007.

**Comment by jankeirse** [comment]
Given the stack trace in that screenshot, there's definitely a problem on either those machines or those users (less likely) and it's probably unrelated to Office. To verify that it is indeed related to the computer, could you have one of the users for whom it does not work try it on your computer where it is known to work with your login and also, try with your login on a computer where it does not work for other users?

**Comment by hmiedemann** [comment]
I can try that. I will do it at some point throughout the day and let you know.

**Comment by hmiedemann** [comment]
Jan,
Sorry for the late response. I have tried using the extension now on multiple different computers, with multiple different user accounts with the same result. I cannot get the extension to work on any Office 2007 product, but it works without issue on any other year.

**Comment by jankeirse** [comment]
That's strange, I use it with Office 2007 without issues.
