### ISSUE TITLE
Network Ports used

### ISSUE THREAD

**Issue by tedlwsn** [jankeirse/tvhgooglemapi#57]
I have been having some issues deploying this to one of our remote offices out in the Netherlands. I need to know which TCP/UDP ports the Google MAPI tool utilize. When the users try to use the tool in our network it doesn't connect /won't work. Once they go home or use a hotspot it works fine. I have a feeling a port is blocked there that isn't blocked in our US office network. 

Thanks,

**Comment by jankeirse** [comment]
Tcp ports 993 and 465.
