### ISSUE TITLE
BCC field doesn't work :( ...... (copies in TO instead)

### ISSUE THREAD

**Issue by pethughes** [jankeirse/tvhgooglemapi#59]
Hi,

I have just been testing this tool to use in my School. It works beautifully for everything we need, except....

When we use our database program to create an email it uses the BCC for confidentiality. But this tool creates the email with the email addresses in the TO field :(

Is this a known issue? Is there anything that we can do?

Thanks,
Pete

**Comment by jankeirse** [comment]
Indeed, that's a bug.  Surprising nobody noticed this before. 

Todo: look at lpMessage->lpRecips[i].ulRecipClass 
and match against:
MAPI_TO
1
Indicates a primary message recipient.
MAPI_CC
2
Indicates a recipient of a message copy.
MAPI_BCC
3
Indicates a recipient of a blind copy.

gmaildrafter can already handle these but the c code doesn't differentiate between them.

**Comment by pethughes** [comment]
Ok, great.

Is gmaildrafter another program you have made that i can use? :)

**Comment by jankeirse** [comment]
gmaildrafter is part of tvhgooglemapi, it's the java part that does the actual call, but the dll doesn't currently pass it the proper input parameters
