### ISSUE TITLE
Google Inbox Support

### ISSUE THREAD

**Issue by BVA64** [jankeirse/tvhgooglemapi#60]
Hi!

I was unable to use this tool with Google Inbox. The mail gets added to the draft folder but it will not open it in the compose window of Inbox. It will only open a browser window to the inbox of Inbox.

It would be great if you could add this feature.

**Comment by jankeirse** [comment]
If anyone who uses inbox wants to provide a patch I'd be happy to accept it.

**Comment by DamSenViet** [comment]
Inbox user here! Definitely needed.

**Comment by benyaminl** [comment]
Is there any work outs? Seems only redirect the link to inbox.google.com/draft.. I tried to look into the inbox behavior but seems no work outs for direct link of a specific draft

**Comment by jankeirse** [comment]
Google inbox is no more.
