### ISSUE TITLE
Draft window not popping up in new Gmail interface 

### ISSUE THREAD

**Issue by jakobkraftt** [jankeirse/tvhgooglemapi#64]
Now that Google has FORCED it's ugly, dumbed-down new interface on its users, the Draft window no longer pops up when creating an email. It's probably a simple fix but I've no idea how to go about it. Hoping someone much smarter than myself will give it a go:)

**Comment by jankeirse** [comment]
I should be an easy fix, at first glance all that's needed is to change the url to https://mail.google.com/mail/u/0/#drafts?compose=<mailid> in Drafter.java. I'll have to see if I can find the time to test that and create a new build.

**Comment by jakobkraftt** [comment]
Thank you for the update!
